# Generated by Django 4.2 on 2026-04-15 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='createAt',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='updateAt',
            new_name='updatedAt',
        ),
    ]
